/* 
 * フォント配信サービス
 *
 * フォント配信サービスのインタフェース仕様です。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ClientAppUpdateInfoData
    /// </summary>
    [DataContract]
    public partial class ClientAppUpdateInfoData : ClientVersionData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientAppUpdateInfoData" /> class.
        /// </summary>
        /// <param name="appId">appId.</param>
        /// <param name="version">version.</param>
        /// <param name="url">url.</param>
        /// <param name="isForcedUpdate">isForcedUpdate</param>
        public ClientAppUpdateInfoData(string appId = default(string), string version = default(string), string url = default(string), bool isForcedUpdate = default(bool))
        : base(appId, version, url)
        {
            this.IsForcedUpdate = isForcedUpdate;
        }

        /// <summary>
        /// Gets or Sets isForcedUpdate
        /// </summary>
        [DataMember(Name = "isForcedUpdate", EmitDefaultValue = false)]
        public bool IsForcedUpdate { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClientAppUpdateInfoData {\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  IsForcedUpdate: ").Append(IsForcedUpdate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClientAppUpdateInfoData);
        }

        /// <summary>
        /// Returns true if ClientAppUpdateInfoData instances are equal
        /// </summary>
        /// <param name="input">Instance of ClientAppUpdateInfoData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClientAppUpdateInfoData input)
        {
            if (input == null)
                return false;

            return
                (
                    this.AppId == input.AppId ||
                    this.AppId.Equals(input.AppId)
                ) &&
                (
                    this.Version == input.Version ||
                    this.Version.Equals(input.Version)
                ) &&
                (
                    this.Url == input.Url ||
                    this.Url.Equals(input.Url)
                )
                &&
                (
                    this.IsForcedUpdate == input.IsForcedUpdate ||
                    this.IsForcedUpdate.Equals(input.IsForcedUpdate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.AppId.GetHashCode();
                hashCode = hashCode * 60 + this.Version.GetHashCode();
                hashCode = hashCode * 72 + this.Url.GetHashCode();
                hashCode = hashCode * 79 + this.IsForcedUpdate.GetHashCode();
                return hashCode;
            }
        }
    }
}
