//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_BTN_SEND {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_BTN_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証コードが違います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_ERR_01 {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しく入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_ERR_02 {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証コードの期限が切れています
        ///もう一度最初からログイン操作を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_ERR_03 {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_ERR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2要素認証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_LBL_AUTHENTICATION_CODE {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_LBL_AUTHENTICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録されているメールアドレスに2要素認証コードを送信しました。
        ///メールの本文に記載されている2要素認証コードを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2要素認証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_BTN_LOGIN {
            get {
                return ResourceManager.GetString("APP_04_01_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスまたはパスワードが違います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_01 {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しく入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_02 {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しく入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_03 {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_Fatal {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_MAILADRESS {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_MAILADRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントをお持ちでない方は に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_REGISTRATION_PAGE {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_REGISTRATION_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードを再設定・お忘れの方は に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_RESET_PASSWORD_PAGE {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_RESET_PASSWORD_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_04_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("APP_04_ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   こちら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_LNK_HERE {
            get {
                return ResourceManager.GetString("APP_04_LNK_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_WIN_TITLE {
            get {
                return ResourceManager.GetString("APP_04_WIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_BTN_NEXT {
            get {
                return ResourceManager.GetString("APP_05_01_BTN_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_DEVICE_LIST_LOGGEDOUG {
            get {
                return ResourceManager.GetString("APP_05_01_DEVICE_LIST_LOGGEDOUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_DEVICE_LIST_LOGOUG {
            get {
                return ResourceManager.GetString("APP_05_01_DEVICE_LIST_LOGOUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSのフォントを使用中のデバイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_DEVICE_LIST_TITLE {
            get {
                return ResourceManager.GetString("APP_05_01_DEVICE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスのログアウトに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_ERR_01 {
            get {
                return ResourceManager.GetString("APP_05_01_ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスのログインに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_ERR_02 {
            get {
                return ResourceManager.GetString("APP_05_01_ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSのフォントは最大２台のデバイスで同時に使用できます。このデバイスで使用したい場合
        ///は、「デバイス管理」より１台以上のデバイスをログアウトしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_05_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回、別のデバイスをご使用の場合には、LETSウェブサイトのデバイス管理ページからも
        ///同様に確認・変更ができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_PROC_DESCRIPTION2 {
            get {
                return ResourceManager.GetString("APP_05_01_PROC_DESCRIPTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在、２台のデバイスでLETSを使用しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_05_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_06_01_BTN_FONTLIST {
            get {
                return ResourceManager.GetString("APP_06_01_BTN_FONTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧ページから使用するフォントをアクティベートしましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_06_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_06_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインが完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_06_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_06_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_BTN_OK {
            get {
                return ResourceManager.GetString("APP_07_01_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート中もLETSのフォントは使用可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_07_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSデスクトップアプリのアップデートを開始します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_07_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_WIN_TITLE {
            get {
                return ResourceManager.GetString("APP_07_01_WIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_BTN_LOGOUT {
            get {
                return ResourceManager.GetString("APP_08_01_BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在行っている作業を保存し、以下の「ログアウト」ボタンを押下してください。
        ///引き続きLETSのフォントを使用する場合は、LETSデスクトップアプリの
        ///クイックメニューからログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_08_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス管理ページからログアウトされたか、
        ///別のデバイスをログインしたために、このデバイスがログアウトされました。
        ///LETSデスクトップアプリをログアウトしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_08_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_WIN_TITLE {
            get {
                return ResourceManager.GetString("APP_08_01_WIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_BTN_CANCEL {
            get {
                return ResourceManager.GetString("APP_09_01_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_BTN_LOGOUT {
            get {
                return ResourceManager.GetString("APP_09_01_BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSデスクトップアプリをログアウトすると、再度ログインするまでこのデバイスで
        ///すべてのLETSのフォントが使えなくなります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_09_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウトします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_09_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムを終了します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_FATAL_UnhandledException_Description {
            get {
                return ResourceManager.GetString("APP_FATAL_UnhandledException_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_FATAL_UnhandledException_MainMassage {
            get {
                return ResourceManager.GetString("APP_FATAL_UnhandledException_MainMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSデスクトップアプリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_TOOLTIP {
            get {
                return ResourceManager.GetString("APP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者権限で起動してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_02_16_ERR_StartAsAdministrators {
            get {
                return ResourceManager.GetString("FUNC_01_02_16_ERR_StartAsAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートできませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_02_17_ERR_UpdateFailed {
            get {
                return ResourceManager.GetString("FUNC_01_02_17_ERR_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントのダウンロードに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_03_01_NOTIFIED_FailedToDownloadFonts {
            get {
                return ResourceManager.GetString("FUNC_01_03_01_NOTIFIED_FailedToDownloadFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のダウンロードに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_03_01_NOTIFIED_FailedToDownloadFonts_Text {
            get {
                return ResourceManager.GetString("FUNC_01_03_01_NOTIFIED_FailedToDownloadFonts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスク容量が不足しています。
        ///ディスクの空き容量を増やしてから再度行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_03_01_NOTIFIED_LackOfDiscSpace {
            get {
                return ResourceManager.GetString("FUNC_01_03_01_NOTIFIED_LackOfDiscSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_APP {
            get {
                object obj = ResourceManager.GetObject("ICON_APP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_COMPLETED {
            get {
                object obj = ResourceManager.GetObject("ICON_COMPLETED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_0 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_1 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_2 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_3 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOGIN {
            get {
                object obj = ResourceManager.GetObject("ICON_LOGIN", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOGOUT {
            get {
                object obj = ResourceManager.GetObject("ICON_LOGOUT", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_NOTIFIED {
            get {
                object obj = ResourceManager.GetObject("ICON_NOTIFIED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("ICON_SELECTED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_DEVICE_PC {
            get {
                object obj = ResourceManager.GetObject("IMG_DEVICE_PC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_LOGO {
            get {
                object obj = ResourceManager.GetObject("IMG_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ログイン処理を利用する場合はコンストラクタの引数に IResourceWrapper, IAuthenticationInformationRepository, IDevicesRepository, IUserStatusRepository, IVolatileSettingRepository を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_AuthenticationService_Login_InvalidOperationException {
            get {
                return ResourceManager.GetString("LOG_ERR_AuthenticationService_Login_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト処理を利用する場合はコンストラクタの引数に IResourceWrapper, IAuthenticationInformationRepository, IUserStatusRepository, IReceiveNotificationRepository, IVolatileSettingRepository, ICustomerRepository, IFontManagerService を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_AuthenticationService_Logout_InvalidOperationException {
            get {
                return ResourceManager.GetString("LOG_ERR_AuthenticationService_Logout_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバから削除されたフォントの一覧を取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_DeletedFontCheck_GetInstallFontInformations {
            get {
                return ResourceManager.GetString("LOG_ERR_DeletedFontCheck_GetInstallFontInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自端末の使用中設定時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_DeviceSettingsViewModel_ActivateUserDevice_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_DeviceSettingsViewModel_ActivateUserDevice_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3台目NG画面の使用中の端末情報取得時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_DeviceSettingsViewModel_InitializeDeviceList_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_DeviceSettingsViewModel_InitializeDeviceList_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自端末のログイン完了時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_DeviceSettingsViewModel_LoginCompleted_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_DeviceSettingsViewModel_LoginCompleted_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当端末の解除に失敗しました({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_DeviceViewModel_DeactivateDevice_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_DeviceViewModel_DeactivateDevice_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェックのお知らせ情報取得処理で例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_ExistsNotificationCheck_unreadNoticeRepository {
            get {
                return ResourceManager.GetString("LOG_ERR_ExistsNotificationCheck_unreadNoticeRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザIDの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontCopyCheck_fontSecurityRepository_GetUserId {
            get {
                return ResourceManager.GetString("LOG_ERR_FontCopyCheck_fontSecurityRepository_GetUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他端末のフォントがコピーされたことを検知しましたが、サーバに通知できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontCopyCheck_fontSecurityRepository_PostFontFileCopyDetection {
            get {
                return ResourceManager.GetString("LOG_ERR_FontCopyCheck_fontSecurityRepository_PostFontFileCopyDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント識別情報取得時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontFileRepository_GetFontInfo_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_FontFileRepository_GetFontInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントファイルの削除に失敗しました。({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontManagerService_DeleteFontFile {
            get {
                return ResourceManager.GetString("LOG_ERR_FontManagerService_DeleteFontFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール対象フォント情報を取得する際にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontManagerService_GetInstallFontInformations {
            get {
                return ResourceManager.GetString("LOG_ERR_FontManagerService_GetInstallFontInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントのダウンロードに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontManagerService_OutOfDiskSpace_Caption {
            get {
                return ResourceManager.GetString("LOG_ERR_FontManagerService_OutOfDiskSpace_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスク容量が不足しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontManagerService_OutOfDiskSpace_Text {
            get {
                return ResourceManager.GetString("LOG_ERR_FontManagerService_OutOfDiskSpace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント情報取得時に例外が発生しましたが、本フォントは {0} は対象外として扱い処理を継続します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontManagerService_UpdateFontsList {
            get {
                return ResourceManager.GetString("LOG_ERR_FontManagerService_UpdateFontsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧の更新処理を利用する場合はコンストラクタの引数に IResourceWrapper, IUserFontsSettingRepository,IFontActivationService, IFontInfoRepository を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_FontManagerService_UpdateFontsList_InvalidOperationException {
            get {
                return ResourceManager.GetString("LOG_ERR_FontManagerService_UpdateFontsList_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン完了画面のフォント一覧画面URL取得処理時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_LoginCompletedViewModel_GetFontListPageUrlException {
            get {
                return ResourceManager.GetString("LOG_ERR_LoginCompletedViewModel_GetFontListPageUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン画面のパスワード再設定ページURL取得処理時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_LoginViewModel_GetResetPasswordPageUrlException {
            get {
                return ResourceManager.GetString("LOG_ERR_LoginViewModel_GetResetPasswordPageUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン画面の会員登録ページURL取得処理時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_LoginViewModel_GetUserRegistrationPageUrlException {
            get {
                return ResourceManager.GetString("LOG_ERR_LoginViewModel_GetUserRegistrationPageUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_LoginViewModel_Login_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_LoginViewModel_Login_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェックの更新情報取得処理で例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_NextVersionCheck_clientApplicationVersionAPIRepository {
            get {
                return ResourceManager.GetString("LOG_ERR_NextVersionCheck_clientApplicationVersionAPIRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェックの起動Ver情報取得処理で例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartingVersionCheck_clientApplicationVersionAPIRepository {
            get {
                return ResourceManager.GetString("LOG_ERR_StartingVersionCheck_clientApplicationVersionAPIRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル実行時にエラーが発生しました。： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartProcessService_StartProcessAdministrator_Win32Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_StartProcessService_StartProcessAdministrator_Win32Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン状態確認時の全端末情報取得処理で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartupService_GetAllDevicesException {
            get {
                return ResourceManager.GetString("LOG_ERR_StartupService_GetAllDevicesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理の契約情報取得で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartupService_GetContractsAggregateException {
            get {
                return ResourceManager.GetString("LOG_ERR_StartupService_GetContractsAggregateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理を利用する場合はコンストラクタの引数にIFontManagerService, IFontManagerService, IContractsAggregateRepository, IUserStatusRepositoryを設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartupService_IsCheckedStartup_InvalidOperationException {
            get {
                return ResourceManager.GetString("LOG_ERR_StartupService_IsCheckedStartup_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2要素認証時に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_TwoFactAuthenticationViewModel_TwoFactAuthentication_Exception {
            get {
                return ResourceManager.GetString("LOG_ERR_TwoFactAuthenticationViewModel_TwoFactAuthentication_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新プログラムのダウンロードに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERROR_ApplicationDownloadService_Fail {
            get {
                return ResourceManager.GetString("LOG_ERROR_ApplicationDownloadService_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生したので、プログラムを終了します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_FATAL_UnhandledException {
            get {
                return ResourceManager.GetString("LOG_FATAL_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新プログラムのダウンロードを開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_ApplicationDownloadService_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_ApplicationDownloadService_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新プログラムのダウンロードが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_ApplicationDownloadService_Success {
            get {
                return ResourceManager.GetString("LOG_INFO_ApplicationDownloadService_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニューを表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_ApplicationIconComponent_tasktrayIcon_Click {
            get {
                return ResourceManager.GetString("LOG_INFO_ApplicationIconComponent_tasktrayIcon_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_DeviceSettingsViewModel_ButtonClick {
            get {
                return ResourceManager.GetString("LOG_INFO_DeviceSettingsViewModel_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3台目NG画面を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_DeviceSettingsViewModel_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_DeviceSettingsViewModel_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ボタンクリック({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_DeviceViewModel_ButtonClick {
            get {
                return ResourceManager.GetString("LOG_INFO_DeviceViewModel_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントの同期処理を実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_NetworkChange_NetworkAvailabilityChanged_ShouldSynchronize {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_NetworkChange_NetworkAvailabilityChanged_ShouldSynchr" +
                        "onize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期確認処理の終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_ScheduledEvent_End {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_ScheduledEvent_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理を実施し、結果は偽 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_ScheduledEvent_IsCheckedStartup_False {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_ScheduledEvent_IsCheckedStartup_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理を実施し、結果は真 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_ScheduledEvent_IsCheckedStartup_True {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_ScheduledEvent_IsCheckedStartup_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知受信処理を開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_ScheduledEvent_ReceiveNotificationStart {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_ScheduledEvent_ReceiveNotificationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフライン→オンラインに変わったときにフォントの同期処理を実行するよう設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_ScheduledEvent_ShouldSynchronize {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_ScheduledEvent_ShouldSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期確認処理の開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_FixedTermScheduler_ScheduledEvent_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_FixedTermScheduler_ScheduledEvent_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_LoginCompletedViewModel_ButtonClick {
            get {
                return ResourceManager.GetString("LOG_INFO_LoginCompletedViewModel_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン完了画面を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_LoginCompletedViewModel_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_LoginCompletedViewModel_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_LoginViewModel_ButtonClick {
            get {
                return ResourceManager.GetString("LOG_INFO_LoginViewModel_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員登録ページリンククリック時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_LoginViewModel_RegistrationPageLinkClick {
            get {
                return ResourceManager.GetString("LOG_INFO_LoginViewModel_RegistrationPageLinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード再設定ページリンククリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_LoginViewModel_ResetPasswordLinkClick {
            get {
                return ResourceManager.GetString("LOG_INFO_LoginViewModel_ResetPasswordLinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}画面を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_LoginViewModel_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_LoginViewModel_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー「アカウント」クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_MenuItemAccountPage_OnAccountMenuItemClick {
            get {
                return ResourceManager.GetString("LOG_INFO_MenuItemAccountPage_OnAccountMenuItemClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー「お知らせ」クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_MenuItemAnnouncePage_OnAnnounceMenuItemClick {
            get {
                return ResourceManager.GetString("LOG_INFO_MenuItemAnnouncePage_OnAnnounceMenuItemClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー「フォント」クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_MenuItemFontListPage_OnFontMenuItemClick {
            get {
                return ResourceManager.GetString("LOG_INFO_MenuItemFontListPage_OnFontMenuItemClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー「ログアウト」クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_MenuItemLogout_OnLogoutMenuItemClick {
            get {
                return ResourceManager.GetString("LOG_INFO_MenuItemLogout_OnLogoutMenuItemClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー「アップデート」クリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_MenuItemUpdate_OnUpdateMenuItemClick {
            get {
                return ResourceManager.GetString("LOG_INFO_MenuItemUpdate_OnUpdateMenuItemClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー状態表示：ダウンロード中を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_QuickMenuComponent_ShowDownloadStatus {
            get {
                return ResourceManager.GetString("LOG_INFO_QuickMenuComponent_ShowDownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー状態表示：ログイン中を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_QuickMenuComponent_ShowLoginStatus {
            get {
                return ResourceManager.GetString("LOG_INFO_QuickMenuComponent_ShowLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クイックメニュー状態表示：アップデート中を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_QuickMenuComponent_ShowUpdateStatus {
            get {
                return ResourceManager.GetString("LOG_INFO_QuickMenuComponent_ShowUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に定期確認処理が実行中のため処理をスキップする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_SchedulerBase_TimerElapsed_ProcessSkip {
            get {
                return ResourceManager.GetString("LOG_INFO_SchedulerBase_TimerElapsed_ProcessSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新バージョンのアプリケーションがインストール済みであるため、操作中のアプリケーションを終了し、再起動します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_Info_StartingVersionCheck_RebootClientApplicatioLOG_Info_StartingVersionCheck_RebootClientApplication {
            get {
                return ResourceManager.GetString("LOG_Info_StartingVersionCheck_RebootClientApplicatioLOG_Info_StartingVersionCheck" +
                        "_RebootClientApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「通知あり」の情報を設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_StartupService_IsCheckedStartup_IsNoticed {
            get {
                return ResourceManager.GetString("LOG_INFO_StartupService_IsCheckedStartup_IsNoticed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト中と判定されたため、以後の起動時チェック処理を行わない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_StartupService_IsCheckedStartup_LoggingOut {
            get {
                return ResourceManager.GetString("LOG_INFO_StartupService_IsCheckedStartup_LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理が正常に終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_StartupService_IsCheckedStartup_Result_True {
            get {
                return ResourceManager.GetString("LOG_INFO_StartupService_IsCheckedStartup_Result_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理の開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_StartupService_IsCheckedStartup_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_StartupService_IsCheckedStartup_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ボタンクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_TwoFactAuthenticationViewModel_ButtonClick {
            get {
                return ResourceManager.GetString("LOG_INFO_TwoFactAuthenticationViewModel_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}画面を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_INFO_TwoFactAuthenticationViewModel_Start {
            get {
                return ResourceManager.GetString("LOG_INFO_TwoFactAuthenticationViewModel_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端末のOS種類が不正です。({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_WARN_DeviceViewModel_InvalidOSTypeException {
            get {
                return ResourceManager.GetString("LOG_WARN_DeviceViewModel_InvalidOSTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ACCOUNT {
            get {
                return ResourceManager.GetString("MENU_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム画面の表示に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ACCOUNT_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("MENU_ACCOUNT_ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム画面のURLが取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ACCOUNT_ERROR_TEXT {
            get {
                return ResourceManager.GetString("MENU_ACCOUNT_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ANNOUNCE {
            get {
                return ResourceManager.GetString("MENU_ANNOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ( {0} 件) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ANNOUNCE_COUNTER {
            get {
                return ResourceManager.GetString("MENU_ANNOUNCE_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書体数：{0}　フォント名：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DOWNLOAD_COMPLETED_TEXT {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_COMPLETED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DOWNLOAD_COMPLETED_TITLE {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_COMPLETED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DOWNLOAD_FONTNAME {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_FONTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DOWNLOAD_LOADING {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FONT {
            get {
                return ResourceManager.GetString("MENU_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧画面の表示に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FONT_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("MENU_FONT_ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧画面のURLが取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FONT_ERROR_TEXT {
            get {
                return ResourceManager.GetString("MENU_FONT_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MailAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_LOGIN_MAILADDRESS {
            get {
                return ResourceManager.GetString("MENU_LOGIN_MAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_LOGIN_USERNAME {
            get {
                return ResourceManager.GetString("MENU_LOGIN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_LOGOUT {
            get {
                return ResourceManager.GetString("MENU_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ( {0} %) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_PROGRESS_RATE {
            get {
                return ResourceManager.GetString("MENU_PROGRESS_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE {
            get {
                return ResourceManager.GetString("MENU_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE_COMPLETED {
            get {
                return ResourceManager.GetString("MENU_UPDATE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE_CONFIRM_CAPTION {
            get {
                return ResourceManager.GetString("MENU_UPDATE_CONFIRM_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSデスクトップアプリのアップデートを開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE_CONFIRM_TEXT {
            get {
                return ResourceManager.GetString("MENU_UPDATE_CONFIRM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE_LOADING {
            get {
                return ResourceManager.GetString("MENU_UPDATE_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントがロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResponseCode_AcountLocked {
            get {
                return ResourceManager.GetString("ResponseCode_AcountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   契約が終了しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResponseCode_ContractExpired {
            get {
                return ResourceManager.GetString("ResponseCode_ContractExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResponseCode_InternalServerError {
            get {
                return ResourceManager.GetString("ResponseCode_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラー(引数不正) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResponseCode_InvalidArgument {
            get {
                return ResourceManager.GetString("ResponseCode_InvalidArgument", resourceCulture);
            }
        }
    }
}
