//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_BTN_SEND {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_BTN_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証コードが違います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_ERR_01 {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しく入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_ERR_02 {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証コードの期限が切れています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_ERR_03 {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_ERR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_LBL_AUTHENTICATION_CODE {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_LBL_AUTHENTICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録されているメールアドレスに認証コードを送信しました。
        ///メールの本文に記載されている認証コードを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ２要素認証コードの入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_2fa_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_04_01_2fa_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_BTN_LOGIN {
            get {
                return ResourceManager.GetString("APP_04_01_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスまたはパスワードが違います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_01 {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しく入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_02 {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しく入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_ERR_03 {
            get {
                return ResourceManager.GetString("APP_04_01_ERR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_MAILADRESS {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_MAILADRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントをお持ちでない方は に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_REGISTRATION_PAGE {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_REGISTRATION_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードを再設定・お忘れの方は に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_LBL_RESET_PASSWORD_PAGE {
            get {
                return ResourceManager.GetString("APP_04_01_LBL_RESET_PASSWORD_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_04_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("APP_04_ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   こちら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_LNK_HERE {
            get {
                return ResourceManager.GetString("APP_04_LNK_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETS アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_04_WIN_TITLE {
            get {
                return ResourceManager.GetString("APP_04_WIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_BTN_NEXT {
            get {
                return ResourceManager.GetString("APP_05_01_BTN_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_DEVICE_LIST_LOGGEDOUG {
            get {
                return ResourceManager.GetString("APP_05_01_DEVICE_LIST_LOGGEDOUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_DEVICE_LIST_LOGOUG {
            get {
                return ResourceManager.GetString("APP_05_01_DEVICE_LIST_LOGOUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSのフォントを使用中のデバイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_DEVICE_LIST_TITLE {
            get {
                return ResourceManager.GetString("APP_05_01_DEVICE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスのログアウトに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_ERR_01 {
            get {
                return ResourceManager.GetString("APP_05_01_ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスのログインに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_ERR_02 {
            get {
                return ResourceManager.GetString("APP_05_01_ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSのフォントは最大２台のデバイスで同時に使用できます。このデバイスで使用したい場合
        ///は、「デバイス管理」より１台以上のデバイスをログアウトしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_05_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSウェブサイトのデバイス管理ページからも同様に確認・変更ができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_PROC_DESCRIPTION2 {
            get {
                return ResourceManager.GetString("APP_05_01_PROC_DESCRIPTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在、２台のデバイスでLETSを使用しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_05_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_05_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_06_01_BTN_FONTLIST {
            get {
                return ResourceManager.GetString("APP_06_01_BTN_FONTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント一覧ページから使用するフォントをアクティベートしましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_06_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_06_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_06_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_06_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_BTN_OK {
            get {
                return ResourceManager.GetString("APP_07_01_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート中もLETSのフォントは使用可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_07_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSデスクトップアプリの強制アップデートを開始します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_07_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_07_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_BTN_LOGOUT {
            get {
                return ResourceManager.GetString("APP_08_01_BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在行っている作業を保存し、以下の「ログアウト」ボタンを押下してください。
        ///引き続きLETSのフォントを使用する場合は、クイックメニューからログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_08_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このデバイスがログアウトされたため、LETSデスクトップアプリを
        ///ログアウトします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_08_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETS アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_08_01_WIN_TITLE {
            get {
                return ResourceManager.GetString("APP_08_01_WIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_BTN_CANCEL {
            get {
                return ResourceManager.GetString("APP_09_01_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_BTN_LOGOUT {
            get {
                return ResourceManager.GetString("APP_09_01_BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LETSデスクトップアプリをログアウトすると、再度ログインするまでこのデバイスで
        ///すべてのLETSのフォントが使えなくなります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_PROC_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_09_01_PROC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウトします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_09_01_PROC_TITLE {
            get {
                return ResourceManager.GetString("APP_09_01_PROC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生したので、プログラムを終了します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APP_ERR_UnhandledException {
            get {
                return ResourceManager.GetString("APP_ERR_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者権限で起動してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_02_16_ERR_StartAsAdministrators {
            get {
                return ResourceManager.GetString("FUNC_01_02_16_ERR_StartAsAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートできませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_02_17_ERR_UpdateFailed {
            get {
                return ResourceManager.GetString("FUNC_01_02_17_ERR_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントのダウンロードに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_03_01_NOTIFIED_FailedToDownloadFonts {
            get {
                return ResourceManager.GetString("FUNC_01_03_01_NOTIFIED_FailedToDownloadFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスク容量が不足しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FUNC_01_03_01_NOTIFIED_LackOfDistSpace {
            get {
                return ResourceManager.GetString("FUNC_01_03_01_NOTIFIED_LackOfDistSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_APP {
            get {
                object obj = ResourceManager.GetObject("ICON_APP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_COMPLETED {
            get {
                object obj = ResourceManager.GetObject("ICON_COMPLETED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_0 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_1 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_2 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOADING_3 {
            get {
                object obj = ResourceManager.GetObject("ICON_LOADING_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOGIN {
            get {
                object obj = ResourceManager.GetObject("ICON_LOGIN", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_LOGOUT {
            get {
                object obj = ResourceManager.GetObject("ICON_LOGOUT", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_NOTIFIED {
            get {
                object obj = ResourceManager.GetObject("ICON_NOTIFIED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ICON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("ICON_SELECTED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_DEVICE_PC {
            get {
                object obj = ResourceManager.GetObject("IMG_DEVICE_PC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_LOGO {
            get {
                object obj = ResourceManager.GetObject("IMG_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ログイン状態確認時の全端末情報取得処理で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartupService_GetAllDevicesException {
            get {
                return ResourceManager.GetString("LOG_ERR_StartupService_GetAllDevicesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理の契約情報取得で例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartupService_GetContractsAggregateException {
            get {
                return ResourceManager.GetString("LOG_ERR_StartupService_GetContractsAggregateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時チェック処理を利用する場合はコンストラクタの引数にIFontManagerService, IContractsAggregateRepositoryを設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERR_StartupService_IsCheckedStartup_InvalidOperationException {
            get {
                return ResourceManager.GetString("LOG_ERR_StartupService_IsCheckedStartup_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ACCOUNT {
            get {
                return ResourceManager.GetString("MENU_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ANNOUNCE {
            get {
                return ResourceManager.GetString("MENU_ANNOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ( {0} 件) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ANNOUNCE_COUNTER {
            get {
                return ResourceManager.GetString("MENU_ANNOUNCE_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DOWNLOAD_FONTNAME {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_FONTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DOWNLOAD_LOADING {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FONT {
            get {
                return ResourceManager.GetString("MENU_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MailAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_LOGIN_MAILADDRESS {
            get {
                return ResourceManager.GetString("MENU_LOGIN_MAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_LOGIN_USERNAME {
            get {
                return ResourceManager.GetString("MENU_LOGIN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_LOGOUT {
            get {
                return ResourceManager.GetString("MENU_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ( {0} %) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_PROGRESS_RATE {
            get {
                return ResourceManager.GetString("MENU_PROGRESS_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE {
            get {
                return ResourceManager.GetString("MENU_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE_COMPLETED {
            get {
                return ResourceManager.GetString("MENU_UPDATE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UPDATE_LOADING {
            get {
                return ResourceManager.GetString("MENU_UPDATE_LOADING", resourceCulture);
            }
        }
    }
}
