/* 
 * フォント配信サービス
 *
 * フォント配信サービスのインタフェース仕様です。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFontApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// フォントダウンロードAPI
        /// </summary>
        /// <remarks>
        /// 指定したID埋め込み済フォントファイルを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetFont(string X_LETS_DEVICEID, string userAgent, string fontId);

        /// <summary>
        /// フォントダウンロードAPI
        /// </summary>
        /// <remarks>
        /// 指定したID埋め込み済フォントファイルを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetFontWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string fontId);
        /// <summary>
        /// フォント一覧画面URLの取得API
        /// </summary>
        /// <remarks>
        /// 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>UrlResponse</returns>
        UrlResponse GetFontListUrl(string X_LETS_DEVICEID, string userAgent);

        /// <summary>
        /// フォント一覧画面URLの取得API
        /// </summary>
        /// <remarks>
        /// 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>ApiResponse of UrlResponse</returns>
        ApiResponse<UrlResponse> GetFontListUrlWithHttpInfo(string X_LETS_DEVICEID, string userAgent);
        /// <summary>
        /// インストールフォント情報の取得API
        /// </summary>
        /// <remarks>
        /// ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>InlineResponse200</returns>
        InlineResponse200 GetInstallFonts(string X_LETS_DEVICEID, string userAgent, string contains);

        /// <summary>
        /// インストールフォント情報の取得API
        /// </summary>
        /// <remarks>
        /// ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>ApiResponse of InlineResponse200</returns>
        ApiResponse<InlineResponse200> GetInstallFontsWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string contains);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFontApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// フォントダウンロードAPI
        /// </summary>
        /// <remarks>
        /// 指定したID埋め込み済フォントファイルを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetFontAsync(string X_LETS_DEVICEID, string userAgent, string fontId);

        /// <summary>
        /// フォントダウンロードAPI
        /// </summary>
        /// <remarks>
        /// 指定したID埋め込み済フォントファイルを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetFontAsyncWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string fontId);
        /// <summary>
        /// フォント一覧画面URLの取得API
        /// </summary>
        /// <remarks>
        /// 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>Task of UrlResponse</returns>
        System.Threading.Tasks.Task<UrlResponse> GetFontListUrlAsync(string X_LETS_DEVICEID, string userAgent);

        /// <summary>
        /// フォント一覧画面URLの取得API
        /// </summary>
        /// <remarks>
        /// 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>Task of ApiResponse (UrlResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<UrlResponse>> GetFontListUrlAsyncWithHttpInfo(string X_LETS_DEVICEID, string userAgent);
        /// <summary>
        /// インストールフォント情報の取得API
        /// </summary>
        /// <remarks>
        /// ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>Task of InlineResponse200</returns>
        System.Threading.Tasks.Task<InlineResponse200> GetInstallFontsAsync(string X_LETS_DEVICEID, string userAgent, string contains);

        /// <summary>
        /// インストールフォント情報の取得API
        /// </summary>
        /// <remarks>
        /// ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>Task of ApiResponse (InlineResponse200)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse200>> GetInstallFontsAsyncWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string contains);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFontApi : IFontApiSync, IFontApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FontApi : IFontApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FontApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FontApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FontApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FontApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FontApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FontApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FontApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FontApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// フォントダウンロードAPI 指定したID埋め込み済フォントファイルを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetFont(string X_LETS_DEVICEID, string userAgent, string fontId)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = GetFontWithHttpInfo(X_LETS_DEVICEID, userAgent, fontId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// フォントダウンロードAPI 指定したID埋め込み済フォントファイルを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> GetFontWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string fontId)
        {
            // verify the required parameter 'X_LETS_DEVICEID' is set
            if (X_LETS_DEVICEID == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'X_LETS_DEVICEID' when calling FontApi->GetFont");

            // verify the required parameter 'userAgent' is set
            if (userAgent == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'userAgent' when calling FontApi->GetFont");

            // verify the required parameter 'fontId' is set
            if (fontId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'fontId' when calling FontApi->GetFont");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/octet-stream",
                "application/json; charset=utf-8"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("fontId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fontId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-LETS-DEVICEID", Org.OpenAPITools.Client.ClientUtils.ParameterToString(X_LETS_DEVICEID)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("User-Agent", Org.OpenAPITools.Client.ClientUtils.ParameterToString(userAgent)); // header parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<System.IO.Stream>("/api/v1/fonts/{fontId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFont", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// フォントダウンロードAPI 指定したID埋め込み済フォントファイルを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetFontAsync(string X_LETS_DEVICEID, string userAgent, string fontId)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await GetFontAsyncWithHttpInfo(X_LETS_DEVICEID, userAgent, fontId);
            return localVarResponse.Data;

        }

        /// <summary>
        /// フォントダウンロードAPI 指定したID埋め込み済フォントファイルを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="fontId"></param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> GetFontAsyncWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string fontId)
        {
            // verify the required parameter 'X_LETS_DEVICEID' is set
            if (X_LETS_DEVICEID == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'X_LETS_DEVICEID' when calling FontApi->GetFont");

            // verify the required parameter 'userAgent' is set
            if (userAgent == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'userAgent' when calling FontApi->GetFont");

            // verify the required parameter 'fontId' is set
            if (fontId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'fontId' when calling FontApi->GetFont");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/octet-stream",
                "application/json; charset=utf-8"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            localVarRequestOptions.PathParameters.Add("fontId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(fontId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-LETS-DEVICEID", Org.OpenAPITools.Client.ClientUtils.ParameterToString(X_LETS_DEVICEID)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("User-Agent", Org.OpenAPITools.Client.ClientUtils.ParameterToString(userAgent)); // header parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<System.IO.Stream>("/api/v1/fonts/{fontId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFont", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// フォント一覧画面URLの取得API 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>UrlResponse</returns>
        public UrlResponse GetFontListUrl(string X_LETS_DEVICEID, string userAgent)
        {
            Org.OpenAPITools.Client.ApiResponse<UrlResponse> localVarResponse = GetFontListUrlWithHttpInfo(X_LETS_DEVICEID, userAgent);
            return localVarResponse.Data;
        }

        /// <summary>
        /// フォント一覧画面URLの取得API 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>ApiResponse of UrlResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<UrlResponse> GetFontListUrlWithHttpInfo(string X_LETS_DEVICEID, string userAgent)
        {
            // verify the required parameter 'X_LETS_DEVICEID' is set
            if (X_LETS_DEVICEID == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'X_LETS_DEVICEID' when calling FontApi->GetFontListUrl");

            // verify the required parameter 'userAgent' is set
            if (userAgent == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'userAgent' when calling FontApi->GetFontListUrl");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json; charset=utf-8"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.HeaderParameters.Add("X-LETS-DEVICEID", Org.OpenAPITools.Client.ClientUtils.ParameterToString(X_LETS_DEVICEID)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("User-Agent", Org.OpenAPITools.Client.ClientUtils.ParameterToString(userAgent)); // header parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<UrlResponse>("/api/v1/screens/font-list/url", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFontListUrl", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// フォント一覧画面URLの取得API 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>Task of UrlResponse</returns>
        public async System.Threading.Tasks.Task<UrlResponse> GetFontListUrlAsync(string X_LETS_DEVICEID, string userAgent)
        {
            Org.OpenAPITools.Client.ApiResponse<UrlResponse> localVarResponse = await GetFontListUrlAsyncWithHttpInfo(X_LETS_DEVICEID, userAgent);
            return localVarResponse.Data;

        }

        /// <summary>
        /// フォント一覧画面URLの取得API 会員サイトの「FON_05_01 フォント一覧ー契約中画面」のURLを返却する。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <returns>Task of ApiResponse (UrlResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<UrlResponse>> GetFontListUrlAsyncWithHttpInfo(string X_LETS_DEVICEID, string userAgent)
        {
            // verify the required parameter 'X_LETS_DEVICEID' is set
            if (X_LETS_DEVICEID == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'X_LETS_DEVICEID' when calling FontApi->GetFontListUrl");

            // verify the required parameter 'userAgent' is set
            if (userAgent == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'userAgent' when calling FontApi->GetFontListUrl");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json; charset=utf-8"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            localVarRequestOptions.HeaderParameters.Add("X-LETS-DEVICEID", Org.OpenAPITools.Client.ClientUtils.ParameterToString(X_LETS_DEVICEID)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("User-Agent", Org.OpenAPITools.Client.ClientUtils.ParameterToString(userAgent)); // header parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<UrlResponse>("/api/v1/screens/font-list/url", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFontListUrl", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// インストールフォント情報の取得API ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>InlineResponse200</returns>
        public InlineResponse200 GetInstallFonts(string X_LETS_DEVICEID, string userAgent, string contains)
        {
            Org.OpenAPITools.Client.ApiResponse<InlineResponse200> localVarResponse = GetInstallFontsWithHttpInfo(X_LETS_DEVICEID, userAgent, contains);
            return localVarResponse.Data;
        }

        /// <summary>
        /// インストールフォント情報の取得API ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>ApiResponse of InlineResponse200</returns>
        public Org.OpenAPITools.Client.ApiResponse<InlineResponse200> GetInstallFontsWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string contains)
        {
            // verify the required parameter 'X_LETS_DEVICEID' is set
            if (X_LETS_DEVICEID == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'X_LETS_DEVICEID' when calling FontApi->GetInstallFonts");

            // verify the required parameter 'userAgent' is set
            if (userAgent == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'userAgent' when calling FontApi->GetInstallFonts");

            // verify the required parameter 'contains' is set
            if (contains == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'contains' when calling FontApi->GetInstallFonts");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json; charset=utf-8"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "contains", contains));
            localVarRequestOptions.HeaderParameters.Add("X-LETS-DEVICEID", Org.OpenAPITools.Client.ClientUtils.ParameterToString(X_LETS_DEVICEID)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("User-Agent", Org.OpenAPITools.Client.ClientUtils.ParameterToString(userAgent)); // header parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<InlineResponse200>("/api/v1/install-fonts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetInstallFonts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// インストールフォント情報の取得API ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>Task of InlineResponse200</returns>
        public async System.Threading.Tasks.Task<InlineResponse200> GetInstallFontsAsync(string X_LETS_DEVICEID, string userAgent, string contains)
        {
            Org.OpenAPITools.Client.ApiResponse<InlineResponse200> localVarResponse = await GetInstallFontsAsyncWithHttpInfo(X_LETS_DEVICEID, userAgent, contains);
            return localVarResponse.Data;

        }

        /// <summary>
        /// インストールフォント情報の取得API ユーザが会員サイトで指定したインストールフォント情報の一覧を返却する。 ユーザーがフォントのディアクティブ⇒アクティブを行ったときに最新のバージョンに書き換える。 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="X_LETS_DEVICEID">デバイス固有のIDを設定する。</param>
        /// <param name="userAgent">LETS/{アプリバージョン} ({OSタイプ} {OSバージョン})</param>
        /// <param name="contains"></param>
        /// <returns>Task of ApiResponse (InlineResponse200)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<InlineResponse200>> GetInstallFontsAsyncWithHttpInfo(string X_LETS_DEVICEID, string userAgent, string contains)
        {
            // verify the required parameter 'X_LETS_DEVICEID' is set
            if (X_LETS_DEVICEID == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'X_LETS_DEVICEID' when calling FontApi->GetInstallFonts");

            // verify the required parameter 'userAgent' is set
            if (userAgent == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'userAgent' when calling FontApi->GetInstallFonts");

            // verify the required parameter 'contains' is set
            if (contains == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'contains' when calling FontApi->GetInstallFonts");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json; charset=utf-8"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "contains", contains));
            localVarRequestOptions.HeaderParameters.Add("X-LETS-DEVICEID", Org.OpenAPITools.Client.ClientUtils.ParameterToString(X_LETS_DEVICEID)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("User-Agent", Org.OpenAPITools.Client.ClientUtils.ParameterToString(userAgent)); // header parameter

            // authentication (BearerAuth) required
            // bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<InlineResponse200>("/api/v1/install-fonts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetInstallFonts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
